name: Build winPEAS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore winPEAS.sln

      - name: Ensure regexes.yaml file
        run: |
          mkdir -p build_lists
          echo "default_content" > build_lists/regexes.yaml # Replace this with actual content or ensure the file exists

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build project
        run: msbuild winPEAS.sln /p:Configuration=Release
