name: Build winPEAS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate build_lists existence
        run: |
          if (Test-Path ./build_lists) {
            Write-Host "Path exists"
          } else {
            Write-Error "Path './build_lists' does not exist"
          }

      - name: Move build_lists
        run: |
          Copy-Item -Path ./build_lists -Destination D:/a/build_lists -Recurse -Force

      - name: Restore NuGet packages
        run: nuget restore winPEAS.sln

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build project
        run: msbuild winPEAS.sln /p:Configuration=Release
