name: Build winPEAS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build project
        run: msbuild /p:Configuration=Release
